receivers:
  prometheus:
    config:
      scrape_configs:
        - job_name: fake-metrics
          scrape_interval: 3s
          static_configs:
            - targets: [ "${env:METRICS_HOST}:${env:METRICS_PORT}" ]
  filelog:
    include: [ "/var/logs/generated.log" ]
    operators:
      - type: json_parser
        timestamp:
          parse_from: attributes.datetime
          layout: "%d/%b/%Y:%H:%M:%S %z"

exporters:
  prometheus:
    endpoint: ":${env:PROMETHEUS_PORT}"

processors:
  metricstransform:
    transforms:
      - include: ^fake_(.*)$
        match_type: regexp
        action: update
        operations:
          - action: add_label
            new_label: origin
            new_value: fake
      - include: ^fake_(.*)$
        match_type: regexp
        action: update
        new_name: $${1}
      - include: ^nodejs_(.*)$
        match_type: regexp
        action: update
        operations:
          - action: add_label
            new_label: origin
            new_value: node
      - include: ^nodejs_(.*)$
        match_type: regexp
        action: update
        new_name: $${1}

connectors:
  count:
    requests.errors:
      description: Number of 500 errors
      condition: [ "status == 500 " ]

service:
  pipelines:
    logs:
      receivers: [ "filelog" ]
      exporters: [ "count" ]
    metrics:
      receivers: [ "prometheus", "count" ]
      processors: [ "metricstransform" ]
      exporters: [ "prometheus" ]
