receivers:
  prometheus:
    config:
      scrape_configs:
        - job_name: fake-metrics
          scrape_interval: 3s
          static_configs:
            - targets: [ "${env:METRICS_HOST}:${env:METRICS_PORT}" ]

exporters:
  prometheus:
    endpoint: ":${env:PROMETHEUS_PORT}"

service:
  pipelines:
    metrics:
      receivers: [ "prometheus" ]
      exporters: [ "prometheus" ]
