receivers:
  prometheus:
    config:
      scrape_configs:
        - job_name: fake-metrics
          scrape_interval: 3s
          static_configs:
            - targets: [ "${env:METRICS_HOST}:${env:METRICS_PORT}" ]
  filelog:
    include: [ "/var/logs/generated.log" ]
    operators:
      - type: json_parser
        timestamp:
          parse_from: attributes.datetime
          layout: "%d/%b/%Y:%H:%M:%S %z"
        severity:
          parse_from: attributes.status
          mapping:
            error: 5xx
            warn: 4xx
            info: 3xx
            debug: 2xx
      - id: remove_body
        type: remove
        field: body
      - id: remove_datetime
        type: remove
        field: attributes.datetime
      - id: remove_status
        type: remove
        field: attributes.status

exporters:
  prometheus:
    endpoint: ":${env:PROMETHEUS_PORT}"
  loki:
    endpoint: "http://loki:3100/loki/api/v1/push"

processors:
  metricstransform:
    transforms:
      - include: ^fake_(.*)$
        match_type: regexp
        action: update
        operations:
          - action: add_label
            new_label: origin
            new_value: fake
      - include: ^fake_(.*)$
        match_type: regexp
        action: update
        new_name: $${1}
      - include: ^nodejs_(.*)$
        match_type: regexp
        action: update
        operations:
          - action: add_label
            new_label: origin
            new_value: node
      - include: ^nodejs_(.*)$
        match_type: regexp
        action: update
        new_name: $${1}

service:
  telemetry:
    logs:
  pipelines:
    logs:
      receivers: [ "filelog" ]
      exporters: [ "loki" ]
    metrics:
      receivers: [ "prometheus" ]
      processors: [ "metricstransform" ]
      exporters: [ "prometheus" ]
